build:
  project: Build\EasyNetQ.proj
  verbosity: minimal
  publish_nuget: false  

test: off              

artifacts:
  - path: Package\**\*.nupkg
 
deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    server:
    api_key:
      secure: PutEncryptedApiKeyHere
    on:
      branch: master
                      
